In [42]:
import pandas as pd

In [43]:
customer = pd.read_excel(r".\Customer Call List.xlsx")

In [44]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [45]:
customer.drop_duplicates(keep='first')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [46]:
customer = customer.drop_duplicates(keep='first')

In [47]:
customer = customer.drop(columns=["Not_Useful_Column"])

In [48]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [49]:
customer.loc[:, 'Last_Name'] = customer['Last_Name'].str.strip("..._/")

In [50]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [51]:
customer.loc[:, "Phone_Number"] = customer["Phone_Number"].str.replace(r'[^a-zA-Z0-9]','', regex=True) # vervang alles wat niet onder regex valt met een lege string

In [52]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [53]:
customer.loc[:, "Phone_Number"] = customer["Phone_Number"].apply(lambda x: str(x)) # alles naar een string zetten om daarna str methode de data te veranderen

In [54]:
customer.loc[:, "Phone_Number"] = customer["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + x[3:6] + "-" + x[6:9])

In [55]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545545-542,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643643-977,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678678-346,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762762-246,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678678-346,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545545-542,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543543-234,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678678-346,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762762-246,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545545-542,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643643-977,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678678-346,"910 Tatooine Road, Tatooine",Yes,N

In [56]:
import re

In [57]:
customer['Phone_Number'].apply(
    lambda x: x[0:4] + x[4:7] + "-" + x[-3:] if isinstance(x, str) and not bool(re.match(r'(?i)^na[n]?-*$', x)) else x
)

0     123-545-542
1     123-643-977
2           nan--
3     123-543-234
4     876-678-346
5     304-762-246
6           nan--
7     876-678-346
8            Na--
9     123-545-542
10          nan--
11          nan--
12    123-543-234
13    876-678-346
14    304-762-246
15    123-545-542
16    123-643-977
17          nan--
18           Na--
19    876-678-346
Name: Phone_Number, dtype: object

-   `re.match():` Deze functie zoekt naar een match aan het begin van de string.
-   `r'(?i)^na[n]?-*$':` Deze regex matcht zowel 'nan' als 'na', ongeacht hoofdlettergevoeligheid, en gevolgd door nul of meer streepjes.
-   `not bool(re.match(...)):` Dit controleert of de regex niet matcht, wat betekent dat de string geen 'nan' of 'na' bevat.

In [58]:
customer.loc[:, 'Phone_Number'] = customer['Phone_Number'].apply(
    lambda x: x[0:4] + x[4:7] + "-" + x[-3:] if isinstance(x, str) and not bool(re.match(r'(?i)^na[n]?-*$', x)) else x
)

In [59]:
import numpy as np

In [60]:
customer['Phone_Number'].apply(
    lambda x: np.nan if pd.isna(x) or pd.Series(x).str.contains(r'(?i)^na[n]?-*$', regex=True).any() else x
)

0     123-545-542
1     123-643-977
2             NaN
3     123-543-234
4     876-678-346
5     304-762-246
6             NaN
7     876-678-346
8             NaN
9     123-545-542
10            NaN
11            NaN
12    123-543-234
13    876-678-346
14    304-762-246
15    123-545-542
16    123-643-977
17            NaN
18            NaN
19    876-678-346
Name: Phone_Number, dtype: object

- np.nan: Dit is de waarde die wordt teruggegeven als de conditie waar is.

- pd.isna(x) or pd.Series(x).str.contains(r'(?i)^na[n]?-*$', regex=True).any(): Dit is de conditie die wordt geëvalueerd. Het gebruikt or om te controleren of x een NaN is of voldoet aan de regex-patroon.

- x: Dit is de waarde die wordt teruggegeven als de conditie onwaar is.

In [61]:
customer.loc[:, 'Phone_Number'] = customer['Phone_Number'].apply(
    lambda x: np.nan if pd.isna(x) or pd.Series(x).str.contains(r'(?i)^na[n]?-*$', regex=True).any() else x
)

In [62]:
customer['Address'].str.split(pat=",", n=2, expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [63]:
customer.loc[:, 'Phone_Number'] = customer['Phone_Number'].apply(
    lambda x: np.nan if pd.isna(x) or pd.Series(x).str.contains(r'(?i)^na[n]?-*$', regex=True).any() else x
)

In [64]:
customer[["Street_Adress","State", "Zip_Code"]] = customer['Address'].str.split(pat=",", n=2, expand=True)

In [65]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [66]:
customer['Paying Customer'].replace({'^Y$': 'Yes', '^N$': 'No'}, regex=True)

0     Yes
1      No
2      No
3     Yes
4     Yes
5     Yes
6      No
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13    Yes
14     No
15     No
16    Yes
17    Yes
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [67]:
customer.loc[:,'Paying Customer'] = customer['Paying Customer'].replace({'^Y$': 'Yes', '^N$': 'No'}, regex=True)

In [68]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,3498 Super Lane,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [69]:
customer.loc[:,'Do_Not_Contact'] = customer['Do_Not_Contact'].replace({'^Y$': 'Yes', '^N$': 'No'}, regex=True)

In [70]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,3498 Super Lane,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None

In [71]:
customer.loc[:, 'Paying Customer'] = customer['Paying Customer'].apply(
    lambda x: np.nan if pd.isna(x) or pd.Series(x).str.contains("N/a").any() else x
)

In [72]:
customer

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,3498 Super Lane,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,NaN,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None

In [76]:
customer_1 = customer.loc[~((customer['Do_Not_Contact'] == 'Yes') | (customer['Phone_Number'].isna()))] #~ draait de True om in False, dus hier wordt alles behouden als er niet ja staat en als phone number niet leeg is,

In [77]:
customer_1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None

In [78]:
customer_1.reset_index(drop=True, inplace=True)

In [79]:
customer_1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
2,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
3,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
4,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
5,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
6,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
7,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
8,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
9,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None

In [80]:
customer_filtered = customer.query("Do_Not_Contact != 'Yes' & Phone_Number.notna()")

In [81]:
customer_filtered

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None

In [82]:
customer_filtered_2 = customer[(customer['Do_Not_Contact'] != 'Yes') & customer['Phone_Number'].notna()]

In [83]:
customer_filtered_2

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Yes,No,123 Dragons Road,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,No,No,98 Clue Drive,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,None