Tesla just provided their quarterly sales for their major vehicles.

Determine which Tesla Model has made the most profit.

Include all columns with the "profit" column at the end.

```python

import pandas as pd;

tesla_models.head()

tesla_models['profit'] = (tesla_models['car_price'] - tesla_models['production_cost']) * tesla_models['cars_sold']


tesla_models = tesla_models.sort_values(by=["profit"], ascending=False)

tesla_models.head(1)

```

```mySQL
SELECT tesla_model, car_price, cars_sold, production_cost,
  (car_price - production_cost) * cars_sold AS profit
FROM tesla_models
ORDER BY profit DESC
LIMIT 1;
```

We need to identify which clients he needs to reach out to and provide that information to Dr. Obrien.

If a patient is over the age of 50, cholesterol level of 240 or over, and weight 200 or greater, then they are at high risk of having a heart attack.

Write a query to retrieve these patients. Include all columns in your output.

As Cholesterol level is the largest indicator, order the output by Cholesterol from Highest to Lowest so he can reach out to them first.

#method1

```python

import pandas as pd

patients.head()

patients_filtered = patients.loc[(patients["age"]> 50) & (patients["cholesterol"] >=240) & (patients["weight"] >=200)]

patients_filtered = patients_filtered.sort_values(by="cholesterol", ascending=False)

patients_filtered
```

#method2
```python
import pandas as pd

patients.head()

patients_queried = patients.query('cholesterol >=240 and weight >=200 and age > 50')

patients_queried = patients_queried.sort_values(by = "cholesterol", ascending=False)

patients_queried
```

```sql
SELECT * 
FROM patients
WHERE age > 50 AND weight >= 200 AND cholesterol >=240
ORDER BY cholesterol DESC
```

```python
import pandas as pd;

bakery_items.head()

filter = bakery_items["product_name"].apply(lambda x: pd.Series(x).str.contains('Chocolate').any() )

Choc = bakery_items[filter]

Choc
```

I love chocolate and only want delicious baked goods that have chocolate in them!

Write a Query to return bakery items that contain the word "Chocolate".

``sql
SELECT *
FROM bakery_items
WHERE product_name like '%Chocolate%'
```

Herschel's Manufacturing Plant has hit some hard times with the economy and unfortunately they need to let some people go.

They figure the younger employees need their jobs more as they are growing families so they decide to let go of their 3 oldest employees. They have more experience and will be able to land on their feet easier (and they had to pay them more).

Write a query to identify the ids of the three oldest employees.

Order output from oldest to youngest.
# SQL METHOD 1
```sql
WITH CTE AS (
    SELECT employee_id, birth_date,
           ROW_NUMBER() OVER (ORDER BY birth_date ASC) AS row_num
    FROM employees
)
SELECT employee_id
FROM CTE
WHERE row_num <= 3
ORDER BY birth_date ASC
```
# SQL METHOD 2
```sql
SELECT employee_id
FROM employees
ORDER BY birth_date ASC
LIMIT 3;
```

# SQL METHOD 3
```sql
SELECT employee_id
FROM employees
WHERE birth_date IN (
    SELECT birth_date
    FROM employees
    ORDER BY birth_date ASC
    LIMIT 3
)
ORDER BY birth_date ASC;
```

```python
import pandas as pd;

employees["birth_day"] = pd.to_datetime(employees["birth_date"])

sorted_employees = employees.sort_values(by='birth_day', ascending=True)

sorted_employees[["employee_id"]].head(3)
```

Yan is a sandwich enthusiast and is determined to try every combination of sandwich possible. He wants to start with every combination of bread and meats and then move on from there, but he wants to do it in a systematic way.

Below we have 2 tables, bread and meats

Output every possible combination of bread and meats to help Yan in his endeavors.

Order by the bread and then meat alphabetically. This is what Yan prefers.

```python

import pandas as pd;

bread_table.head()

cart_comb  = bread_table.merge(meat_table, how="cross")

comb = cart_comb[["bread_name", "meat_name"]].sort_values(by=["bread_name","meat_name"], ascending=True)

```

```sql
SELECT bread_table.bread_name, meat_table.meat_name

FROM bread_table

CROSS JOIN meat_table

ORDER BY bread_name ASC, meat_name ASC
```

Cars need to be inspected every year in order to pass inspection and be street legal. If a car has any critical issues it will fail inspection or if it has more than 3 minor issues it will also fail.

Write a query to identify all of the cars that passed inspection.

Output should include the owner name and vehicle name. Order by the owner name alphabetically.

```python
import pandas as pd;

inspections_filtered = inspections.query("critical_issues == 0 and minor_issues<=3")

inspections_filtered= inspections_filtered.sort_values(by="owner_name", ascending=True)

end_result = inspections_filtered[["owner_name", "vehicle"]]

```


```sql

SELECT owner_name, vehicle 

FROM inspections

WHERE minor_issues <= 3 AND critical_issues = 0

ORDER BY owner_name ASC
```

Return all the candidate IDs that have problem solving skills, SQL experience, knows Python or R, and has domain knowledge.

Order output on IDs from smallest to largest.

```sql
Return all the candidate IDs that have problem solving skills, SQL experience, knows Python or R, and has domain knowledge.

Order output on IDs from smallest to largest.
```

```python

import pandas as pd;

candidates_filt = candidates.query("sql_experience == 'X' and domain_knowledge == 'X' and problem_solving == 'X' and (python == 'X'or r_programming == 'X') ")

result = candidates_filt[["candidate_id"]]

```

Costco is known for their rotisserie chickens they sell, not just because they are delicious, but because they are a loss leader in this area.

This means they actually lose money in selling the chickens, but they are okay with this because they make up for that in other areas.

Using the sales table, calculate how much money they have lost on their rotisserie chickens this year. Round to the nearest whole number.

```python
total_loss = round(sales["lost_revenue_millions"].sum())
```

```sql
SELECT ROUND(sum(lost_revenue_millions))

FROM sales
```

If a customer is 55 or above they qualify for the senior citizen discount. Check which customers qualify.

Assume the current date 1/1/2023.

Return all of the Customer IDs who qualify for the senior citizen discount in ascending order.

```sql
SELECT customer_id AS discount_IDS
FROM customers
WHERE birth_date <= "1968-01-01"
ORDER BY customer_id ASC
```

```python
import pandas as pd;
customers["birth_date"] = pd.to_datetime(customers["birth_date"])

customers_filtered = customers.query("birth_date <= '1968-01-01'")

customers_filtered_sorted = customers_filtered.sort_values(by="customer_id", ascending=True)

result = customers_filtered_sorted[["customer_id"]]
```

Write a query to determine the popularity of a post on LinkedIn

Popularity is defined by number of actions (likes, comments, shares, etc.) divided by the number impressions the post received * 100.

If the post receives a score higher than 1 it was very popular.

Return all the post IDs and their popularity where the score is 1 or greater.

Order popularity from highest to lowest.

```python

linkedin_posts["popularity"] = (linkedin_posts["actions"]/linkedin_posts["impressions"])*100

linkedin_posts_filt = linkedin_posts.loc[linkedin_posts["popularity"] >= 1]

result = linkedin_posts_filt[["post_id", "popularity"]].sort_values(by="popularity", ascending=False)
```

```sql
SELECT post_id, ((actions/impressions)*100) AS popularity
FROM linkedin_posts
WHERE (actions / impressions) * 100 >= 1
ORDER BY popularity DESC
```